package net.runelite.client.plugins.microbot.kspdirectfishing;

import lombok.extern.slf4j.Slf4j;
import net.runelite.api.*;
import net.runelite.api.coords.WorldPoint;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.ObjectID;
import net.runelite.client.plugins.microbot.*;
import net.runelite.client.plugins.microbot.Script;
import net.runelite.client.plugins.microbot.api.npc.models.Rs2NpcModel;
import net.runelite.client.plugins.microbot.api.tileobject.models.Rs2TileObjectModel;
import net.runelite.client.plugins.microbot.util.bank.Rs2Bank;
import net.runelite.client.plugins.microbot.util.camera.Rs2Camera;
import net.runelite.client.plugins.microbot.util.inventory.*;
import net.runelite.client.plugins.microbot.util.keyboard.Rs2Keyboard;
import net.runelite.client.plugins.microbot.util.player.Rs2Player;
import net.runelite.client.plugins.microbot.util.walker.Rs2Walker;
import net.runelite.client.plugins.microbot.util.widget.Rs2Widget;
import java.awt.event.KeyEvent;
import java.util.*;
import java.util.concurrent.TimeUnit;

@Slf4j
public class KspDirectFishingScript extends Script {
    private static final int DIRECT_BANK_OBJECT_SEARCH_RADIUS=20,DIRECT_FIRE_DISTANCE=4,INVALID_DIRECT_BANK_OBJECT_ID=10527;
    private static final long BANK_OPEN_RETRY_DELAY=3_000,FIRE_STATUS_REFRESH_DELAY=1_500,FISH_INTERACTION_TIMEOUT=15_000,FAILED_CLICK_RETRY_DELAY=750;
    private static final int[] SUPPORTED_FIRE_IDS={ObjectID.FIRE,ObjectID.FORESTRY_FIRE,ObjectID.EAGLEPEAK_CAMPFIRE_TIDY,ObjectID.FIRE_COOK,43475};
    private KspDirectFishingConfig config; private KspDirectFishingMode mode; private KspDirectFishingLocation location;
    private volatile KspDirectFishingState state=KspDirectFishingState.STARTING; private volatile String status="Starting"; private volatile WorldPoint fishingAnchor,lastFirePoint; private volatile boolean fireAvailable;
    private long lastFishingClick,lastFailedFishingClick,lastBankOpenAttempt,lastFireStatusCheck; private boolean bankOpenRequested,bankRequired;

    public KspDirectFishingState getState(){return state;} public String getStatus(){return status;} public WorldPoint getFishingAnchor(){return fishingAnchor;} public boolean isFireAvailable(){return fireAvailable;} public WorldPoint getLastFirePoint(){return lastFirePoint;} public KspDirectFishingLocation getLocation(){return location;}
    public boolean isDropMode(){return config!=null&&(config.dropFish()||config.fishingLocation().isForceDrop());}
    public int getRawFishCount(){if(mode==null)return 0;switch(mode){case SHRIMP_ANCHOVIES:return Rs2Inventory.count(ItemID.RAW_SHRIMP)+Rs2Inventory.count(ItemID.RAW_ANCHOVIES);case SARDINE_HERRING:return Rs2Inventory.count(ItemID.RAW_SARDINE)+Rs2Inventory.count(ItemID.RAW_HERRING);default:return 0;}}
    public int getBaitCount(){return mode==null||!mode.usesBait()?0:Rs2Inventory.itemQuantity(ItemID.FISHING_BAIT);}
    public boolean run(KspDirectFishingConfig config){this.config=config;mode=config.fishingMode();location=config.fishingLocation();state=KspDirectFishingState.STARTING;status="Locating "+location;lastFishingClick=lastFailedFishingClick=lastBankOpenAttempt=lastFireStatusCheck=0;bankOpenRequested=bankRequired=fireAvailable=false;fishingAnchor=lastFirePoint=null;mainScheduledFuture=scheduledExecutorService.scheduleWithFixedDelay(this::loop,0,250,TimeUnit.MILLISECONDS);return true;}

    private void loop(){try{if(!super.run()||!Microbot.isLoggedIn())return;if(Rs2Bank.isOpen()&&state!=KspDirectFishingState.BANKING&&!bankRequired){Rs2Bank.closeBank();return;}mode=config.fishingMode();KspDirectFishingLocation selected=config.fishingLocation();if(location!=selected){location=selected;fishingAnchor=null;bankOpenRequested=bankRequired=false;}if(isDropMode())updateFireStatus(null);else refreshFireStatusIfDue();if(fishingAnchor==null){Rs2NpcModel s=findNearestFishingSpot();if(s!=null)fishingAnchor=s.getWorldLocation();}state=determineState();switch(state){case FISHING:handleFishing();break;case DROPPING:handleDropping();break;case WALKING_TO_FISH:case RETURNING_TO_FISH:handleReturnToFishing();break;case FINDING_FIRE:case WALKING_TO_FIRE:case USING_FIRE:case WAITING_FOR_COOK_INTERFACE:case COOKING:case WAITING_FOR_FIRE:handleCookingFlow();break;case WALKING_TO_BANK:case BANKING:handleBanking();break;case STARTING:handleStart();break;default:break;}}catch(Exception ex){state=KspDirectFishingState.ERROR;status="Error - check client log";log.error("KSP Direct Fishing loop error",ex);sleep(1_500);}}
    private KspDirectFishingState determineState(){if(bankRequired)return Rs2Bank.isOpen()?KspDirectFishingState.BANKING:KspDirectFishingState.WALKING_TO_BANK;boolean supplies=hasFishingSupplies(),full=Rs2Inventory.isFull();if(isDropMode()&&hasCaughtFish()&&(full||!supplies))return KspDirectFishingState.DROPPING;if(!supplies){bankRequired=true;return Rs2Bank.isOpen()?KspDirectFishingState.BANKING:KspDirectFishingState.WALKING_TO_BANK;}if(full){if(!isDropMode()&&hasCookableRawFish())return KspDirectFishingState.FINDING_FIRE;bankRequired=true;return Rs2Bank.isOpen()?KspDirectFishingState.BANKING:KspDirectFishingState.WALKING_TO_BANK;}return findNearestFishingSpot()!=null?KspDirectFishingState.FISHING:KspDirectFishingState.WALKING_TO_FISH;}
    private void handleStart(){Rs2NpcModel s=findNearestFishingSpot();if(s!=null){fishingAnchor=s.getWorldLocation();status="Fishing spot locked: "+location;state=KspDirectFishingState.FISHING;}else walkToFishingLocation();}
    private void handleFishing(){if(Rs2Player.isMoving()||Rs2Inventory.isFull()||!hasFishingSupplies())return;Rs2NpcModel s=findNearestFishingSpot();if(s==null){walkToFishingLocation();return;}WorldPoint p=s.getWorldLocation();if(p!=null)fishingAnchor=p;if((Rs2Player.isAnimating()||Rs2Player.isInteracting())&&System.currentTimeMillis()-lastFishingClick<FISH_INTERACTION_TIMEOUT){status="Fishing "+mode+" at "+location;return;}long now=System.currentTimeMillis();if(now-lastFailedFishingClick<FAILED_CLICK_RETRY_DELAY){status="Waiting to retry fishing";return;}String action=mode.getPrimaryAction();status="Direct click: "+action;if(s.click(action)){lastFishingClick=now;lastFailedFishingClick=0;Rs2Player.waitForXpDrop(Skill.FISHING,true);while(!Thread.currentThread().isInterrupted()&&Microbot.isLoggedIn()&&!Rs2Inventory.isFull()&&hasFishingSupplies()&&(Rs2Player.isAnimating()||Rs2Player.isInteracting()))Rs2Player.waitForXpDrop(Skill.FISHING,10_000,true);}else{lastFailedFishingClick=now;status="Fishing click failed: "+action;}}
    private void handleDropping(){status=location.isForceDrop()?"Dropping fish - Lumbridge mode":"Dropping fish";Rs2Inventory.dropAll(i->isRawFishName(i.getName()));sleepUntil(()->!hasCaughtFish(),5_000);if(!hasFishingSupplies()){bankRequired=true;status="Fish dropped - restocking supplies";}else status=hasCaughtFish()?"Dropping fish - retrying":"Fish dropped - continuing";}

    private void handleCookingFlow(){if(isDropMode()){state=KspDirectFishingState.DROPPING;status="Drop mode active";return;}if(!hasCookableRawFish()){bankRequired=true;state=KspDirectFishingState.WALKING_TO_BANK;status="Cooking complete - banking";return;}Rs2TileObjectModel fire=findNearestFire();if(fire==null){if(config.waitForFire()){state=KspDirectFishingState.WAITING_FOR_FIRE;status="Waiting for Fire / Forester's Campfire";}else{bankRequired=true;state=KspDirectFishingState.WALKING_TO_BANK;status="No fire found - banking raw fish";}return;}WorldPoint p=getTileObjectWorldPoint(fire);if(p==null){updateFireStatus(null);status="Fire location unavailable";return;}fireAvailable=true;lastFirePoint=p;turnCameraTowardCampfire(p);if(Rs2Player.getWorldLocation().distanceTo(p)>DIRECT_FIRE_DISTANCE){state=KspDirectFishingState.WALKING_TO_FIRE;status="Walking to nearest fire";Rs2Walker.walkTo(p,DIRECT_FIRE_DISTANCE);sleepUntil(()->!Rs2Player.isMoving()||Rs2Player.getWorldLocation().distanceTo(p)<=3,10_000);return;}state=KspDirectFishingState.USING_FIRE;status="Preparing fish for fire";cookAllOn(fire);}
    private void cookAllOn(Rs2TileObjectModel fire){while(!Thread.currentThread().isInterrupted()&&Microbot.isLoggedIn()&&hasCookableRawFish()){if(Rs2Player.isMoving()){state=KspDirectFishingState.WALKING_TO_FIRE;status="Finishing movement to fire";return;}if(Rs2Player.isAnimating()||Rs2Player.isInteracting()){state=KspDirectFishingState.COOKING;status="Cooking in progress";sleepUntil(()->!Rs2Player.isAnimating()&&!Rs2Player.isInteracting(),15_000);}String raw=firstCookableRawFish();if(raw==null){bankRequired=true;status="Cooking complete - banking";return;}Integer id=Microbot.getClientThread().invoke(fire::getId);if(id==null){updateFireStatus(null);state=KspDirectFishingState.FINDING_FIRE;status="Fire disappeared";return;}state=KspDirectFishingState.USING_FIRE;status="Turning camera to campfire";WorldPoint p=getTileObjectWorldPoint(fire);if(p!=null)turnCameraTowardCampfire(p);status="Using "+raw+" on fire";Rs2Inventory.useUnNotedItemOnObject(raw,id);state=KspDirectFishingState.WAITING_FOR_COOK_INTERFACE;status="Waiting for cook interface";if(!sleepUntil(()->Rs2Widget.findWidget("How many would you like to cook?",null)!=null,3_500)){state=KspDirectFishingState.FINDING_FIRE;status="Cook interface did not open";sleep(1_000,1_600);return;}status="Starting "+raw;Rs2Keyboard.keyPress(KeyEvent.VK_SPACE);if(!sleepUntil(()->Rs2Player.isAnimating()||Rs2Player.getAnimation()!=AnimationID.IDLE,5_000)){state=KspDirectFishingState.WAITING_FOR_COOK_INTERFACE;status="Cooking did not start - retrying";sleep(800,1_300);return;}state=KspDirectFishingState.COOKING;status="Cooking "+raw;Rs2Player.waitForXpDrop(Skill.COOKING,true);String current=raw;sleepUntilTrue(()->!Rs2Inventory.hasItem(current)&&!Rs2Player.isAnimating(3_500),500,150_000);}bankRequired=true;state=KspDirectFishingState.WALKING_TO_BANK;status="Cooking complete - banking";}

    private void handleBanking(){if(Rs2Bank.isOpen()){bankOpenRequested=false;lastBankOpenAttempt=0;state=KspDirectFishingState.BANKING;bankInventoryAndRestock();return;}if(config.directBankFirst()){Rs2TileObjectModel booth=null;Rs2NpcModel banker=null;try{booth=Microbot.getRs2TileObjectCache().query().withName("Bank booth").where(o->o.getName()!=null&&"Bank booth".equalsIgnoreCase(o.getName())&&o.getId()!=INVALID_DIRECT_BANK_OBJECT_ID).within(DIRECT_BANK_OBJECT_SEARCH_RADIUS).nearestOnClientThread();banker=Microbot.getRs2NpcCache().query().withName("Banker").where(n->n.getName()!=null&&"Banker".equalsIgnoreCase(n.getName())).fromWorldView().nearestOnClientThread();}catch(RuntimeException ex){log.debug("Bank target query failed: {}",ex.getMessage());}if(booth!=null||banker!=null){state=KspDirectFishingState.BANKING;long now=System.currentTimeMillis();if(!bankOpenRequested){bankOpenRequested=true;lastBankOpenAttempt=now;boolean clicked=booth!=null&&booth.click("Bank");if(!clicked&&banker!=null)clicked=banker.click("Bank");status=clicked?"Waiting for bank to open":"Bank target click failed";sleepUntil(Rs2Bank::isOpen,5_000);if(Rs2Bank.isOpen()){bankOpenRequested=false;lastBankOpenAttempt=0;}return;}if(now-lastBankOpenAttempt<BANK_OPEN_RETRY_DELAY){status="Waiting for bank to open";return;}bankOpenRequested=false;status="Bank open timed out - retrying";return;}}bankOpenRequested=false;state=KspDirectFishingState.WALKING_TO_BANK;status="Walking to nearest bank";if(!Rs2Player.isMoving())Rs2Bank.walkToBank();}
    private void bankInventoryAndRestock(){status="Banking / restocking";Set<Integer> keep=new HashSet<>();for(String item:mode.getRequiredItems()){Rs2ItemModel i=Rs2Inventory.get(item);if(i!=null)keep.add(i.getId());}if(keep.isEmpty())Rs2Bank.depositAll();else Rs2Bank.depositAllExcept(keep.toArray(new Integer[0]));Rs2Inventory.waitForInventoryChanges(1_500);if(mode==KspDirectFishingMode.SHRIMP_ANCHOVIES){if(!withdrawSupply("Small fishing net",false))return;}else if(!withdrawSupply("Fishing rod",false)||!withdrawSupply("Fishing bait",true))return;if(!hasFishingSupplies()){failAndStop("Could not obtain required fishing supplies");return;}Rs2Bank.closeBank();sleepUntil(()->!Rs2Bank.isOpen(),3_000);bankOpenRequested=bankRequired=false;lastBankOpenAttempt=0;fishingAnchor=null;state=KspDirectFishingState.RETURNING_TO_FISH;status="Returning to "+location;}
    private boolean withdrawSupply(String item,boolean all){if(Rs2Inventory.hasItem(item))return true;if(!Rs2Bank.hasItem(item)){failAndStop(item+" not found in bank");return false;}status="Withdrawing "+item.toLowerCase(Locale.ROOT);if(all)Rs2Bank.withdrawAll(item);else Rs2Bank.withdrawOne(item);sleepUntil(()->Rs2Inventory.hasItem(item),3_500);return true;}
    private void handleReturnToFishing(){if(Rs2Inventory.isFull()||!hasFishingSupplies()){if(isDropMode()&&hasCaughtFish()){state=KspDirectFishingState.DROPPING;return;}bankRequired=true;status="Banking required before fishing";return;}Rs2NpcModel s=findNearestFishingSpot();if(s==null){walkToFishingLocation();return;}WorldPoint p=s.getWorldLocation();if(p!=null)fishingAnchor=p;long now=System.currentTimeMillis();if(now-lastFailedFishingClick<FAILED_CLICK_RETRY_DELAY){status="Waiting to retry fishing";return;}String action=mode.getPrimaryAction();state=KspDirectFishingState.FISHING;status="Direct return: "+action;if(s.click(action)){lastFishingClick=now;lastFailedFishingClick=0;status="Fishing "+mode+" at "+location;}else{lastFailedFishingClick=now;state=KspDirectFishingState.RETURNING_TO_FISH;status="Return click failed: "+action;}}
    private void walkToFishingLocation(){WorldPoint here=Rs2Player.getWorldLocation(),target=location.getAnchor();state=KspDirectFishingState.WALKING_TO_FISH;if(location.contains(here)){status="Waiting for fishing spot at "+location;return;}status="Walking to "+location;if(!Rs2Player.isMoving())Rs2Walker.walkTo(target,4);}

    private Rs2NpcModel findNearestFishingSpot(){int[] ids=mode.getFishingSpotIds();try{return Microbot.getRs2NpcCache().query().where(n->matchesId(ids,n.getId())&&location.contains(n.getWorldLocation())).nearestOnClientThread();}catch(RuntimeException ex){if(!Thread.currentThread().isInterrupted())log.debug("Fishing spot query failed: {}",ex.getMessage());return null;}}
    private void turnCameraTowardCampfire(WorldPoint p){if(p==null)return;try{int a=(Rs2Camera.angleToTile(p)-90)%360;if(a<0)a+=360;Rs2Camera.setAngle(a,25);}catch(RuntimeException ex){log.debug("Camera turn toward campfire failed: {}",ex.getMessage());}}
    private void refreshFireStatusIfDue(){long now=System.currentTimeMillis();if(now-lastFireStatusCheck<FIRE_STATUS_REFRESH_DELAY)return;lastFireStatusCheck=now;try{updateFireStatus(queryNearestFire());}catch(RuntimeException ex){updateFireStatus(null);log.debug("Fire status refresh failed: {}",ex.getMessage());}}
    private Rs2TileObjectModel findNearestFire(){try{Rs2TileObjectModel f=queryNearestFire();updateFireStatus(f);return f;}catch(RuntimeException ex){updateFireStatus(null);if(!Thread.currentThread().isInterrupted())log.debug("Fire query failed: {}",ex.getMessage());return null;}}
    private Rs2TileObjectModel queryNearestFire(){return Microbot.getRs2TileObjectCache().query().withIds(SUPPORTED_FIRE_IDS).within(config.fireSearchRadius()).nearestOnClientThread();}
    private void updateFireStatus(Rs2TileObjectModel f){fireAvailable=f!=null;lastFirePoint=f==null?null:getTileObjectWorldPoint(f);}
    private WorldPoint getTileObjectWorldPoint(Rs2TileObjectModel o){if(o==null)return null;try{return Microbot.getClientThread().invoke(o::getWorldLocation);}catch(RuntimeException ex){log.debug("Tile object location lookup failed: {}",ex.getMessage());return null;}}
    private boolean hasFishingSupplies(){return mode==KspDirectFishingMode.SHRIMP_ANCHOVIES?Rs2Inventory.hasItem("Small fishing net"):Rs2Inventory.hasItem("Fishing rod")&&Rs2Inventory.hasItem("Fishing bait");}
    private boolean hasCaughtFish(){if(mode==null)return false;for(String raw:mode.getRawFish())if(Rs2Inventory.hasItem(raw))return true;return false;}
    private boolean isRawFishName(String name){if(name==null||mode==null)return false;for(String raw:mode.getRawFish())if(raw.equalsIgnoreCase(name))return true;return false;}
    private static boolean matchesId(int[] ids,int id){for(int candidate:ids)if(candidate==id)return true;return false;}
    private boolean hasCookableRawFish(){return firstCookableRawFish()!=null;} private String firstCookableRawFish(){for(String raw:mode.getRawFish())if(Rs2Inventory.hasItem(raw)&&Rs2Player.getSkillRequirement(Skill.COOKING,requiredCookingLevel(raw)))return raw;return null;} private int requiredCookingLevel(String raw){return "Raw herring".equalsIgnoreCase(raw)?5:1;}
    private void failAndStop(String message){state=KspDirectFishingState.ERROR;status=message;Microbot.showMessage(message);log.error(message);shutdown();}
    @Override public void shutdown(){bankRequired=bankOpenRequested=false;state=KspDirectFishingState.STARTING;status="Stopped";super.shutdown();}
}
