package net.runelite.client.plugins.microbot.kspaccountbuilder.tasks.questing.romeoandjuliet.romeoscript;

public enum RomeoState
{
    PREPARING,
    WALKING_TO_CADAVA_BUSH,
    PICKING_CADAVA_BERRIES,
    WALKING_TO_ROMEO,
    TALKING_TO_ROMEO,
    WALKING_TO_JULIET_HALLWAY,
    CLIMBING_TO_JULIET,
    OPENING_JULIET_DOORS,
    WAITING_FOR_CUTSCENE,
    LEAVING_JULIET_HOUSE,
    TALKING_TO_JULIET,
    RETURNING_MESSAGE_TO_ROMEO,
    MESSAGE_DELIVERED,
    WALKING_TO_FATHER_LAWRENCE,
    TALKING_TO_FATHER_LAWRENCE,
    WALKING_TO_APOTHECARY,
    TALKING_TO_APOTHECARY,
    RETURNING_POTION_TO_JULIET,
    GAVE_POTION_TO_JULIET,
    RETURNING_TO_ROMEO,
    TALKING_TO_ROMEO_FINAL,
    COMPLETE
}
