package net.runelite.client.plugins.microbot.kspbankorganizer;

import java.util.*;
import javax.inject.Inject;
import lombok.extern.slf4j.Slf4j;
import net.runelite.client.plugins.microbot.Microbot;
import net.runelite.client.plugins.microbot.util.Global;
import net.runelite.client.plugins.microbot.util.bank.Rs2Bank;

@Slf4j
final class BankOrganizerEngine {
    private final BankSnapshotReader snapshotReader; private final BankActuator actuator; private final SmartSorter sorter; private final AutoCategorizer categorizer;
    private volatile String phase="Idle",lastMessage=""; private volatile OperationMode activeMode=OperationMode.PREVIEW; private volatile int plannedCount,movedCount,sortedCount,misplacedCount; private volatile BankSnapshot latestSnapshot;
    private volatile Map<Integer,ItemCategory> categoriesById=Collections.emptyMap(); private volatile Map<Integer,Integer> targetsById=Collections.emptyMap();
    @Inject BankOrganizerEngine(BankSnapshotReader reader,BankActuator actuator,SmartSorter sorter,AutoCategorizer categorizer){snapshotReader=reader;this.actuator=actuator;this.sorter=sorter;this.categorizer=categorizer;}
    RunResult run(KspBankOrganizerConfig c){return run(c,c.operationMode());}
    RunResult run(KspBankOrganizerConfig c,OperationMode mode){reset(mode);try{setPhase("Opening bank");if(!actuator.ensureBankOpen())return fail("Could not open the nearest bank.");categorizer.configure(c);BankSnapshot initial=readSnapshot();List<PlannedItem> plan=buildPlan(initial,c);plannedCount=plan.size();misplacedCount=countMisplaced(initial);if(mode==OperationMode.PREVIEW){setPhase("Preview complete");lastMessage="Previewed "+plannedCount+" bank stacks; "+misplacedCount+" are outside their mapped destination.";return RunResult.ok(lastMessage,movedCount,sortedCount);}int baselineCount=initial.stackCount();Map<Integer,Integer> baseline=quantityMap(initial);setPhase("Preparing bank rearrangement");BankActuator.ActuatorResult swap=actuator.ensureBankSwapMode();if(!swap.success())return fail(swap.message());setPhase("Moving categories");String error=executeCategoryMoves(plan,c,baselineCount,baseline);if(error!=null)return fail(error);if(c.sortWithinTabs()){BankActuator.ActuatorResult insert=actuator.ensureBankInsertMode();if(!insert.success())return fail(insert.message());setPhase("Smart sorting");error=sortConfiguredTabs(plan,c,baselineCount,baseline);if(error!=null)return fail(error);}BankSnapshot last=readSnapshot();error=verifyUnchanged(baselineCount,baseline,last);if(error!=null)return fail("Final bank verification failed: "+error);misplacedCount=countMisplaced(last);if(c.closeBankWhenFinished())Rs2Bank.closeBank();setPhase("Complete");lastMessage="Organized bank: moved "+movedCount+" stacks and sorted "+sortedCount+" positions. Bank quantities verified.";return RunResult.ok(lastMessage,movedCount,sortedCount);}catch(Throwable t){log.warn("KSP Bank Organizer execution failed",t);return fail(t.getMessage()==null?t.getClass().getSimpleName():t.getMessage());}}

    private List<PlannedItem> buildPlan(BankSnapshot s,KspBankOrganizerConfig c){List<PlannedItem> raw=new ArrayList<>();Map<Integer,ItemCategory> categories=new HashMap<>();Map<ItemCategory,Integer> configured=new EnumMap<>(ItemCategory.class);for(BankSnapshot.BankStack stack:s.items()){ItemCategory category=categorizer.categorize(stack);int target=targetFor(category,c);configured.putIfAbsent(category,target);categories.put(stack.itemId(),category);raw.add(new PlannedItem(stack.itemId(),stack.name(),category,target));}List<ItemCategory> tabs=new ArrayList<>();for(ItemCategory category:ItemCategory.values())if(configured.getOrDefault(category,-1)>0)tabs.add(category);tabs.sort(Comparator.comparingInt((ItemCategory x)->configured.getOrDefault(x,Integer.MAX_VALUE)).thenComparingInt(Enum::ordinal));Map<ItemCategory,Integer> effective=new EnumMap<>(ItemCategory.class);int physical=1;for(ItemCategory category:tabs)effective.put(category,physical++);List<PlannedItem> plan=new ArrayList<>(raw.size());Map<Integer,Integer> targets=new HashMap<>();for(PlannedItem item:raw){int configuredTarget=item.targetTab(),target=configuredTarget<=0?configuredTarget:effective.getOrDefault(item.category(),configuredTarget);plan.add(new PlannedItem(item.itemId(),item.name(),item.category(),target));targets.put(item.itemId(),target);}categoriesById=Collections.unmodifiableMap(categories);targetsById=Collections.unmodifiableMap(targets);return plan;}
    private String executeCategoryMoves(List<PlannedItem> plan,KspBankOrganizerConfig c,int baselineCount,Map<Integer,Integer> baseline){BankSnapshot start=readSnapshot();Map<Integer,Integer> sourceTabs=new HashMap<>();for(BankSnapshot.BankStack s:start.items())sourceTabs.put(s.itemId(),s.tab());List<PlannedItem> ordered=new ArrayList<>(plan);ordered.sort(Comparator.comparingInt(PlannedItem::targetTab).thenComparingInt(p->sourceTabs.getOrDefault(p.itemId(),99)).thenComparing(sorter.comparator(c)));for(PlannedItem p:ordered){if(Thread.currentThread().isInterrupted())return "Organizer interrupted.";int target=p.targetTab();if(target<0)continue;BankSnapshot.BankStack current=stackByItemId(readSnapshot(),p.itemId());if(current==null)return "Could not find "+p.name()+" ("+p.itemId()+") before moving it.";if(current.tab()==target)continue;if(wouldCollapseSourceTab(current.tab()))return "Safety stop: moving "+p.name()+" would empty bank tab "+current.tab()+" and shift later tab indices. Add another stack to that tab, remap it, or move it manually first.";BankActuator.ActuatorResult move;if(target==0)move=actuator.moveToMain(p.itemId(),current.tab());else if(actuator.tabCount(target)>0)move=actuator.moveToExistingTab(p.itemId(),current.tab(),target);else{if(!c.createMissingTabs())return "Destination tab "+target+" does not exist and Create missing tabs is disabled.";int appendable=actuator.realTabCount()+1;if(target!=appendable)return "Cannot create destination tab "+target+" yet; the next appendable bank tab is "+appendable+". Empty destination gaps cannot be created in OSRS.";move=actuator.moveToNewTab(p.itemId(),current.tab());}if(!move.success())return p.name()+": "+move.message();movedCount++;if(c.strictVerification()){BankSnapshot after=readSnapshot();String v=verifyUnchanged(baselineCount,baseline,after);if(v!=null)return "After moving "+p.name()+": "+v;}}return null;}
    private String sortConfiguredTabs(List<PlannedItem> plan,KspBankOrganizerConfig c,int baselineCount,Map<Integer,Integer> baseline){Set<Integer> tabs=new TreeSet<>();for(PlannedItem p:plan)if(p.targetTab()>0)tabs.add(p.targetTab());for(int tab:tabs){if(actuator.tabCount(tab)<=0)continue;BankActuator.ActuatorResult opened=actuator.openTab(tab);if(!opened.success())return opened.message();BankSnapshot first=readSnapshot();List<PlannedItem> desired=desiredPresent(plan,tabStacks(first,tab),tab,c);for(int pos=0;pos<desired.size();pos++){if(Thread.currentThread().isInterrupted())return "Organizer interrupted while sorting.";BankSnapshot snapshot=readSnapshot();List<BankSnapshot.BankStack> stacks=tabStacks(snapshot,tab);if(pos>=stacks.size())return "Tab "+tab+" has fewer stacks than expected during sorting.";int id=desired.get(pos).itemId();if(stacks.get(pos).itemId()==id)continue;int sourcePos=indexOf(stacks,id);if(sourcePos<0)return "Could not find item "+id+" while sorting tab "+tab+".";if(sourcePos<pos)return "Sorting prefix drifted in tab "+tab+".";BankSnapshot.BankStack source=stacks.get(sourcePos),target=stacks.get(pos);if(source.segment()!=target.segment())return "Placeholder boundary changed while sorting tab "+tab+".";BankActuator.ActuatorResult drag=actuator.moveWithinOpenTab(source,target);if(!drag.success())return "Tab "+tab+": "+drag.message();sortedCount++;int prefix=pos+1;if(!Global.sleepUntil(()->{BankSnapshot after=safeReadSnapshot();return after!=null&&isOrderedPrefix(after,desired,tab,prefix);},5000))return "Tab "+tab+" order was not verified after moving "+source.name()+".";if(c.strictVerification()){String v=verifyUnchanged(baselineCount,baseline,readSnapshot());if(v!=null)return "Tab "+tab+": "+v;}}}return null;}
    private List<PlannedItem> desiredPresent(List<PlannedItem> plan,List<BankSnapshot.BankStack> stacks,int tab,KspBankOrganizerConfig c){Set<Integer> ids=new HashSet<>();Map<Integer,Integer> segment=new HashMap<>();for(BankSnapshot.BankStack s:stacks){ids.add(s.itemId());segment.put(s.itemId(),s.segment());}List<PlannedItem> desired=new ArrayList<>();for(PlannedItem p:plan)if(p.targetTab()==tab&&ids.contains(p.itemId()))desired.add(p);desired.sort(Comparator.comparingInt((PlannedItem p)->segment.getOrDefault(p.itemId(),Integer.MAX_VALUE)).thenComparing(sorter.comparator(c)));return desired;}
    private static boolean isOrderedPrefix(BankSnapshot s,List<PlannedItem> desired,int tab,int length){List<BankSnapshot.BankStack> stacks=tabStacks(s,tab);if(stacks.size()<length||desired.size()<length)return false;for(int i=0;i<length;i++)if(stacks.get(i).itemId()!=desired.get(i).itemId())return false;return true;}
    private boolean wouldCollapseSourceTab(int tab){return tab>0&&actuator.tabCount(tab)<=1;} private BankSnapshot readSnapshot(){return latestSnapshot=snapshotReader.read();} private BankSnapshot safeReadSnapshot(){try{return readSnapshot();}catch(Throwable ignored){return null;}}
    private static List<BankSnapshot.BankStack> tabStacks(BankSnapshot s,int tab){List<BankSnapshot.BankStack> out=new ArrayList<>();for(BankSnapshot.BankStack stack:s.items())if(stack.tab()==tab)out.add(stack);out.sort(Comparator.comparingInt(BankSnapshot.BankStack::allItemsIndex));return out;}
    private static int indexOf(List<BankSnapshot.BankStack> stacks,int id){for(int i=0;i<stacks.size();i++)if(stacks.get(i).itemId()==id)return i;return-1;} private static BankSnapshot.BankStack stackByItemId(BankSnapshot s,int id){for(BankSnapshot.BankStack stack:s.items())if(stack.itemId()==id)return stack;return null;}
    private int countMisplaced(BankSnapshot s){int count=0;for(BankSnapshot.BankStack stack:s.items()){Integer target=targetsById.get(stack.itemId());if(target!=null&&target>=0&&stack.tab()!=target)count++;}return count;}
    private static Map<Integer,Integer> quantityMap(BankSnapshot s){Map<Integer,Integer> q=new HashMap<>();for(BankSnapshot.BankStack stack:s.items())q.merge(stack.itemId(),stack.quantity(),Integer::sum);return q;}
    private static String verifyUnchanged(int count,Map<Integer,Integer> baseline,BankSnapshot s){if(s.stackCount()!=count)return "bank stack count changed from "+count+" to "+s.stackCount()+".";return quantityMap(s).equals(baseline)?null:"one or more item quantities changed during organization.";}
    private static int targetFor(ItemCategory category,KspBankOrganizerConfig c){BankTarget t;switch(category){case TELEPORTS:t=c.teleportsTarget();break;case GEAR:t=c.gearTarget();break;case POTIONS:t=c.potionsTarget();break;case FOOD:t=c.foodTarget();break;case SKILLING:t=c.skillingTarget();break;case RAW_MATERIALS:t=c.materialsTarget();break;case HIGH_ALCH:t=c.highAlchTarget();break;case CURRENCY:t=c.currencyTarget();break;default:t=c.questMiscTarget();}return t.getTabIndex();}
    private void reset(OperationMode mode){activeMode=mode==null?OperationMode.PREVIEW:mode;phase="Starting";lastMessage="";plannedCount=movedCount=sortedCount=misplacedCount=0;latestSnapshot=null;categoriesById=Collections.emptyMap();targetsById=Collections.emptyMap();}
    private void setPhase(String value){phase=value;Microbot.status="Bank Organizer: "+value;log.info("Bank Organizer phase: {}",value);} private RunResult fail(String message){phase="Stopped";lastMessage=message==null||message.isEmpty()?"Unknown organizer error.":message;Microbot.status="Bank Organizer: "+lastMessage;log.warn("Bank Organizer stopped: {}",lastMessage);return RunResult.fail(lastMessage,movedCount,sortedCount);}
    String phase(){return phase;} OperationMode activeMode(){return activeMode;} String lastMessage(){return lastMessage;} int plannedCount(){return plannedCount;} int movedCount(){return movedCount;} int sortedCount(){return sortedCount;} int misplacedCount(){return misplacedCount;} BankSnapshot latestSnapshot(){return latestSnapshot;} Map<Integer,ItemCategory> categoriesById(){return categoriesById;} Map<Integer,Integer> targetsById(){return targetsById;}
    void markStoppedByUser(){phase="Stopped";lastMessage="Stopped by user.";Microbot.status="Bank Organizer: Stopped by user.";}
    static final class RunResult{private final boolean success;private final String message;private final int moved,sorted;private RunResult(boolean success,String message,int moved,int sorted){this.success=success;this.message=message;this.moved=moved;this.sorted=sorted;}static RunResult ok(String m,int moved,int sorted){return new RunResult(true,m,moved,sorted);}static RunResult fail(String m,int moved,int sorted){return new RunResult(false,m,moved,sorted);}boolean success(){return success;}String message(){return message;}int moved(){return moved;}int sorted(){return sorted;}}
}
